### PR TITLE
feat(driver/git): checkout branch, tag, commit

### PR DESCRIPTION
**Pull request by maximee-leroyy**
This allows us to have this kind of config:

```
    - name: smlib
      type: git
      repo: https://github.com/bcserv/smlib
      version: transitional_syntax
      unpack:
      - source: /scripting/include
        dest: /addons/sourcemod/scripting/include

```

### CODE REVIEW

**Comment by tmick0** [comment]
Hey, thanks for contributing this - this is great to have.

One concern is that when selecting a branch, I think the modeled `version` field should not be that branch name - otherwise, updates might not automatically be pulled in when that branch is updated.

As is, it should work fine for tags, though.

I'll test this out when I have time and see if I can get it working.

**Comment by maximee-leroyy** [comment]
> Hey, thanks for contributing this - this is great to have.
> 
> One concern is that when selecting a branch, I think the modeled `version` field should not be that branch name - otherwise, updates might not automatically be pulled in when that branch is updated.
> 
> As is, it should work fine for tags, though.
> 
> I'll test this out when I have time and see if I can get it working.

mhh we can just do a  `git fetch` then a `git reset --hard origin/$ref` with $ref being a tag/branch/commit so that if people want to stick to a specific version, they specify a commit, if they want an "auto-update" just the branch/tag name

**Comment by tmick0** [comment]
Good call, that seems to have the intended behavior. It took me some time to remember how everything went together - it has been a while since I worked on it :)

The following implementation appears to work as intended, if you would like to update the PR with it.

```
    def update(self, mgr):
        loc = os.path.join(self._ctx._path, '.sourceknight', 'cache', self._model.name)
        
        fetched = False
        if os.path.isdir(loc):
            repo = git.Repo(loc)
        else:
            logging.info(' Cloning from {:s}'.format(self._model.params['repo']))
            repo = git.Repo.clone_from(self._model.params['repo'], loc)
            fetched = True

        if self._model.version is None:
            if not fetched:
                logging.info(' Pulling from {:s}'.format(repo.remote().url))
                repo.remote().pull()
            self._model.version = repo.head.commit.hexsha
        else:
            if not fetched:
                logging.info(' Fetching from {:s}'.format(repo.remote().url))
                repo.remote().fetch()
            repo.head.reset(self._model.version, working_tree=True)

        self._ctx._state.update(dependencies={
            self._model.name: self._model.state(location=os.path.relpath(loc, self._ctx._path), driver='git')
        })
```

**Comment by tmick0** [comment]
Merged with the suggested patch above

**Pull request merged**
