### PR TITLE
chore: only use pyproject.toml, bump dependencies

### PR DESCRIPTION
**Pull request by maximee-leroyy**

### CODE REVIEW

**Comment by maximee-leroyy** [comment]
cc @tmick0

**Comment by tmick0** [comment]
My bad, lost track of this. Will merge right away.

**Comment by tmick0** [comment]
Let me know if you need a release cut for the updated deps

**Comment by maximee-leroyy** [comment]
thanks! not needed for me since i do:
```
pip install git+https://github.com/tmick0/sourceknight@master
```

**Pull request merged**
